// Renders every logo-derived asset from assets/brand/logo.webp.
// Run with `npm run icons` after replacing the logo; the output is committed.
import { writeFile } from "node:fs/promises";
import sharp from "sharp";

const root = new URL("../", import.meta.url);
const source = new URL("assets/brand/logo.webp", root);

/**
 * The artwork is a coloured mark on a white or transparent background. This
 * removes any white background (pixels close to white become transparent, with
 * a soft edge so the outline stays smooth), trims the empty margin and centres
 * the mark on a transparent square.
 */
async function prepareMark() {
  const { data, info } = await sharp(source.pathname)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  // How far below pure white the darkest channel must be for a pixel to be fully opaque.
  const SOFT_EDGE = 48;
  const { width, height } = info;
  let left = width;
  let top = height;
  let right = 0;
  let bottom = 0;

  for (let y = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1) {
      const offset = (y * width + x) * 4;
      // Some exports already carry transparency; respect it and only key out white where opaque.
      const existing = data[offset + 3] / 255;
      const darkest = Math.min(data[offset], data[offset + 1], data[offset + 2]);
      const keyed = Math.min(1, (255 - darkest) / SOFT_EDGE);
      const alpha = existing * keyed;
      if (existing === 1 && keyed > 0 && keyed < 1) {
        // Edge pixels are a blend with white; recover the mark's own colour.
        for (let channel = 0; channel < 3; channel += 1) {
          const value = (data[offset + channel] - 255 * (1 - alpha)) / alpha;
          data[offset + channel] = Math.max(0, Math.min(255, Math.round(value)));
        }
      }
      data[offset + 3] = Math.round(alpha * 255);
      // Track the mark's bounding box, ignoring faint specks.
      if (alpha > 0.5) {
        left = Math.min(left, x);
        right = Math.max(right, x);
        top = Math.min(top, y);
        bottom = Math.max(bottom, y);
      }
    }
  }

  const box = { left, top, width: right - left + 1, height: bottom - top + 1 };
  const cut = await sharp(data, { raw: { width, height, channels: 4 } })
    .extract(box)
    .png()
    .toBuffer();

  const side = Math.max(box.width, box.height);
  return sharp({
    create: { width: side, height: side, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } },
  })
    .composite([{ input: cut, gravity: "centre" }])
    .png()
    .toBuffer();
}

const mark = await prepareMark();

/** The logo on a transparent square, as a PNG buffer. */
async function logo(size) {
  return sharp(mark).resize(size, size, { kernel: "lanczos3" }).png({ compressionLevel: 9 }).toBuffer();
}

/** The logo centred on an opaque white square, covering `scale` of its width. */
async function onWhite(size, scale) {
  const inner = Math.round(size * scale);
  return sharp({ create: { width: size, height: size, channels: 4, background: "#ffffff" } })
    .composite([{ input: await logo(inner), gravity: "centre" }])
    .flatten({ background: "#ffffff" })
    .png({ compressionLevel: 9 })
    .toBuffer();
}

/** Wraps PNG images in an ICO container (PNG-in-ICO is supported by all current browsers). */
function ico(images) {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(images.length, 4);
  let offset = 6 + images.length * 16;
  const entries = images.map(({ size, data }) => {
    const entry = Buffer.alloc(16);
    entry.writeUInt8(size === 256 ? 0 : size, 0);
    entry.writeUInt8(size === 256 ? 0 : size, 1);
    entry.writeUInt16LE(1, 4);
    entry.writeUInt16LE(32, 6);
    entry.writeUInt32LE(data.length, 8);
    entry.writeUInt32LE(offset, 12);
    offset += data.length;
    return entry;
  });
  return Buffer.concat([header, ...entries, ...images.map((image) => image.data)]);
}

async function save(path, data) {
  await writeFile(new URL(path, root), data);
  console.log(`${path}  ${data.length} bytes`);
}

await save("public/logo.png", await logo(512));
await save("public/icons/icon-192.png", await logo(192));
await save("public/icons/icon-512.png", await logo(512));
// Maskable icons keep the whole logo inside the central safe zone.
await save("public/icons/icon-maskable-512.png", await onWhite(512, 0.62));
// iOS has no transparency for home screen icons, so this one sits on white.
await save("app/apple-icon.png", await onWhite(180, 0.78));
await save("app/icon.png", await logo(96));
await save(
  "app/favicon.ico",
  ico(await Promise.all([16, 32, 48].map(async (size) => ({ size, data: await logo(size) })))),
);

// Inlined into the generated social sharing image, which cannot read files at request time.
// Large enough to stay sharp when it is the only thing on the sharing card.
const inline = (await logo(512)).toString("base64");
await save(
  "lib/brand/logo-data-uri.ts",
  `// Generated by scripts/generate-icons.mjs. Do not edit by hand.\nexport const LOGO_DATA_URI =\n  "data:image/png;base64,${inline}";\n`,
);
